// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDtweLEgx41xRj1aUI24LKShU_YKunCo34',
//     appId: '1:981924797525:android:180ec8b74eff4c6ff188dc',
//     messagingSenderId: '981924797525',
//     projectId: 'test-startup-namer',
//     storageBucket: 'test-startup-namer.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBHmOpBj-I3JgVnKJv6mRGvQh-vXnRExJs',
//     appId: '1:981924797525:ios:d0b873edeaa15b00f188dc',
//     messagingSenderId: '981924797525',
//     projectId: 'test-startup-namer',
//     storageBucket: 'test-startup-namer.appspot.com',
//     iosClientId:
//         '981924797525-bqn8doe6qbh4erlphr85gq5b08974b9p.apps.googleusercontent.com',
//     iosBundleId: 'com.example.getxdemo',
//   );
// }
